# Generated by Django 5.2.12 on 2026-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funded', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=50)),
                ('campaign_address', models.CharField(max_length=255)),
                ('campaign_approval_address', models.CharField(max_length=255)),
            ],
        ),
    ]
