# Generated by Django 5.2.12 on 2026-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='transaction.transaction'),
        ),
    ]
