# Generated by Django 5.2.12 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
