# Generated by Django 5.2.12 on 2026-05-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaign_funded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='transactions',
        ),
    ]
