# Generated by Django 5.2.12 on 2026-05-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_remove_campaign_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
