# Generated by Django 5.2.12 on 2026-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(choices=[('africa', 'Africa'), ('antarctica', 'Antarctica'), ('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('oceania', 'Oceania'), ('south_america', 'South America')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=50)),
            ],
        ),
    ]
