# Generated by Django 5.2.12 on 2026-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
