# Generated by Django 5.2.12 on 2026-05-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('startupper', 'Startupper'), ('investor', 'Investor'), ('judge', 'Judge'), ('visitor', 'Visitor')], max_length=50),
        ),
    ]
